baseURL = "/"
title = "SCATTER PODCAST"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "SCATTER PODCAST"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "AN ANALYTICS AND DATA SCIENCE PODCAST" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Scatter Podcast, hosted by Javier Orraca and Joel Dayrit, explores data analytics, insights, and data science in business. Our blog features business insights and career development advice written by Jonathan Tesser."

    # The name to display in the copyright section in the footer
    copyrightname = "SCATTER PODCAST"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    linkedin = "https://www.linkedin.com/company/scatter-podcast/"
    soundcloud = "https://soundcloud.com/scatterpodcast"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "post"
    name = "Blog"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20
    
  [[menu.main]]
    identifier = "podcast"
    name = "Episodes"
    url = "/podcast/"       # The path can lead to a content folder too.
    weight = 30  

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true